# Generated by Django 6.0.4 on 2026-04-13 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="builditem",
            options={"ordering": ["-added_at"], "verbose_name_plural": "Build Items"},
        ),
        migrations.AlterModelOptions(
            name="part",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Parts"},
        ),
        migrations.AddField(
            model_name="part",
            name="description",
            field=models.TextField(
                blank=True, help_text="Detailed specifications and description"
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Component image", null=True, upload_to="parts/"
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="manufacturer",
            field=models.CharField(
                blank=True, help_text="Brand/Manufacturer name", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_STOCK", "In Stock"),
                    ("OUT_OF_STOCK", "Out of Stock"),
                    ("DISCONTINUED", "Discontinued"),
                ],
                default="IN_STOCK",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pcbuild",
            name="description",
            field=models.TextField(
                blank=True, help_text="Detailed build guide (supports Markdown)"
            ),
        ),
        migrations.AddField(
            model_name="pcbuild",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Build showcase image",
                null=True,
                upload_to="builds/",
            ),
        ),
        migrations.AddField(
            model_name="pcbuild",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Make this build visible to other users"
            ),
        ),
        migrations.AddField(
            model_name="pcbuild",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of the build name",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="wattage",
            field=models.IntegerField(
                blank=True,
                help_text="Power consumption in watts",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
