# Generated by Django 6.0.4 on 2026-04-13 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0002_alter_builditem_options_alter_part_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_parts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="pcbuild",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_builds", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
